replicaCount: 2

image:
  repository: sambitpritamnayak/simple-mvn-prod
  pullPolicy: IfNotPresent
  tag: "1.21.1"

imagePullSecrets: []
nameOverride: "prod-app"
fullnameOverride: "prod-deployment"

service:
  type: ClusterIP
  port: 80

ingress:
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

autoscaling:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

